In [3]:
pip install pandera

Collecting pandera
  Obtaining dependency information for pandera from https://files.pythonhosted.org/packages/8a/8c/f9b264751778afda2d5f9fb977560c2646747efdcbef72c002abae5d80ab/pandera-0.18.3-py3-none-any.whl.metadata
  Using cached pandera-0.18.3-py3-none-any.whl.metadata (15 kB)
Collecting multimethod<=1.10.0 (from pandera)
  Obtaining dependency information for multimethod<=1.10.0 from https://files.pythonhosted.org/packages/7f/bd/750245e47e7f307d9f94d4fa84727f4ed9956005dfa671d58be1d531a0f6/multimethod-1.10-py3-none-any.whl.metadata
  Using cached multimethod-1.10-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: numpy>=1.19.0 in /Users/daynacole/anaconda3/envs/dev/lib/python3.10/site-packages (from pandera) (1.24.3)
Requirement already satisfied: packaging>=20.0 in /Users/daynacole/anaconda3/envs/dev/lib/python3.10/site-packages (from pandera) (23.1)
Requirement already satisfied: pandas>=1.2.0 in /Users/daynacole/anaconda3/envs/dev/lib/python3.10/site-packages (from pandera) (2.0.3)
Collecting pydantic (from pandera)
  Obtaining dependency information for pydantic from https://files.pythonhosted.org/packages/16/ca/330c4f3bd983bb24ac12c7fd1e08c26c8aed70bc64498cf38c770321067f/pydantic-2.7.0-py3-none-any.whl.metadata
  Downloading pydantic-2.7.0-py3-none-any.whl.metadata (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.4/103.4 kB 1.1 MB/s eta 0:00:0000:0100:01
Collecting typeguard>=3.0.2 (from pandera)
  Obtaining dependency information for typeguard>=3.0.2 from https://files.pythonhosted.org/packages/d9/59/e02336eb478ccdfc9bb0d4c27ce04a4260cd8b45aa04f6b00bcfdbb66a2a/typeguard-4.2.1-py3-none-any.whl.metadata
  Using cached typeguard-4.2.1-py3-none-any.whl.metadata (3.7 kB)
Collecting typing-inspect>=0.6.0 (from pandera)
  Obtaining dependency information for typing-inspect>=0.6.0 from https://files.pythonhosted.org/packages/65/f3/107a22063bf27bdccf2024833d3445f4eea42b2e598abfbd46f6a63b6cb0/typing_inspect-0.9.0-py3-none-any.whl.metadata
  Using cached typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: wrapt in /Users/daynacole/anaconda3/envs/dev/lib/python3.10/site-packages (from pandera) (1.14.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/daynacole/anaconda3/envs/dev/lib/python3.10/site-packages (from pandas>=1.2.0->pandera) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/daynacole/anaconda3/envs/dev/lib/python3.10/site-packages (from pandas>=1.2.0->pandera) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/daynacole/anaconda3/envs/dev/lib/python3.10/site-packages (from pandas>=1.2.0->pandera) (2023.3)
Collecting typing-extensions>=4.10.0 (from typeguard>=3.0.2->pandera)
  Obtaining dependency information for typing-extensions>=4.10.0 from https://files.pythonhosted.org/packages/01/f3/936e209267d6ef7510322191003885de524fc48d1b43269810cd589ceaf5/typing_extensions-4.11.0-py3-none-any.whl.metadata
  Downloading typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: mypy-extensions>=0.3.0 in /Users/daynacole/anaconda3/envs/dev/lib/python3.10/site-packages (from typing-inspect>=0.6.0->pandera) (1.0.0)
Collecting annotated-types>=0.4.0 (from pydantic->pandera)
  Obtaining dependency information for annotated-types>=0.4.0 from https://files.pythonhosted.org/packages/28/78/d31230046e58c207284c6b2c4e8d96e6d3cb4e52354721b944d3e1ee4aa5/annotated_types-0.6.0-py3-none-any.whl.metadata
  Downloading annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.18.1 (from pydantic->pandera)
  Obtaining dependency information for pydantic-core==2.18.1 from https://files.pythonhosted.org/packages/d4/77/9add41d5abb5dbb77d203e467ea5ba948f97f825f77c87bbb6a461f2035c/pydantic_core-2.18.1-cp310-cp310-macosx_10_12_x86_64.whl.metadata
  Downloading pydantic_core-2.18.1-cp310-cp310-macosx_10_12_x86_64.whl.metadata (6.5 kB)
Requirement already satisfied: six>=1.5 in /Users/daynacole/anaconda3/envs/dev/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pandera) (1.16.0)
Using cached pandera-0.18.3-py3-none-any.whl (210 kB)
Using cached multimethod-1.10-py3-none-any.whl (9.9 kB)
Using cached typeguard-4.2.1-py3-none-any.whl (34 kB)
Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading pydantic-2.7.0-py3-none-any.whl (407 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 407.9/407.9 kB 7.4 MB/s eta 0:00:00ta 0:00:01
Downloading pydantic_core-2.18.1-cp310-cp310-macosx_10_12_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 23.0 MB/s eta 0:00:0000:0100:01
Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Installing collected packages: typing-extensions, multimethod, annotated-types, typing-inspect, typeguard, pydantic-core, pydantic, pandera
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.4.3 requires pyqt5<5.16, which is not installed.
spyder 5.4.3 requires pyqtwebengine<5.16, which is not installed.
Successfully installed annotated-types-0.6.0 multimethod-1.10 pandera-0.18.3 pydantic-2.7.0 pydantic-core-2.18.1 typeguard-4.2.1 typing-extensions-4.11.0 typing-inspect-0.9.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
#dependencies 
import pandas as pd
import pandera as pa

In [7]:
# pull in oscars demographic data into dataframe
oscars_demo_df = pd.read_csv('Raw Data/Oscars-demographics-DFE.csv', encoding= 'unicode_escape')

oscars_demo_df.head(10)

FileNotFoundError: [Errno 2] No such file or directory: 'Raw Data/Oscars-demographics-DFE.csv'

In [25]:
# check for null values
oscars_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441 entries, 0 to 440
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   _unit_id                       441 non-null    int64
 1   _golden                        441 non-null    bool
 2   _unit_state                    441 non-null    object
 3   _trusted_judgments             441 non-null    int64
 4   _last_judgment_at              416 non-null    object
 5   birthplace                     441 non-null    object
 6   birthplace:confidence          441 non-null    float64
 7   date_of_birth                  441 non-null    object
 8   date_of_birth:confidence       441 non-null    float64
 9   race_ethnicity                 441 non-null    object
 10  race_ethnicity:confidence      441 non-null    float64
 11  religion                       441 non-null    object
 12  religion:confidence            441 non-null    float64
 13  sexual_orientation             441 non-null    object
 14  sexual_orientation:confidence  441 non-null    float64
 15  year_of_award                  441 non-null    int64
 16  year_of_award:confidence       441 non-null    float64
 17  award                          441 non-null    object
 18  biourl                         441 non-null    object
 19  birthplace_gold                9 non-null      object
 20  date_of_birth_gold             8 non-null      object
 21  movie                          441 non-null    object
 22  person                         441 non-null    object
 23  race_ethnicity_gold            2 non-null      object
 24  religion_gold                  10 non-null     object
 25  sexual_orientation_gold        3 non-null      object
 26  year_of_award_gold             11 non-null     float64
dtypes: bool(1), float64(7), int64(3), object(16)
memory usage: 90.1+ KB

In [26]:
# since many columns contain nearly all nulls, we will drop the irrelevant ones
oscars_demo_df= oscars_demo_df.drop(columns=['_unit_id','_golden','_unit_state','_trusted_judgments','_last_judgment_at','birthplace:confidence','date_of_birth:confidence','race_ethnicity:confidence','religion:confidence','sexual_orientation:confidence','year_of_award:confidence','birthplace_gold','date_of_birth_gold','race_ethnicity_gold','religion_gold','sexual_orientation_gold','year_of_award_gold'])

In [27]:
#check to for null values once columns have been removed
oscars_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441 entries, 0 to 440
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   birthplace          441 non-null    object
 1   date_of_birth       441 non-null    object
 2   race_ethnicity      441 non-null    object
 3   religion            441 non-null    object
 4   sexual_orientation  441 non-null    object
 5   year_of_award       441 non-null    int64
 6   award               441 non-null    object
 7   biourl              441 non-null    object
 8   movie               441 non-null    object
 9   person              441 non-null    object
dtypes: int64(1), object(9)
memory usage: 34.6+ KB

In [30]:
oscars_demo_df.head(10)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,biourl,movie,person
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,http://www.nndb.com/people/320/000043191/,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,http://www.nndb.com/people/626/000042500/,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,http://www.nndb.com/people/320/000043191/,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,http://www.nndb.com/people/544/000041421/,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,http://www.nndb.com/people/292/000044160/,Bad Girl,Frank Borzage
5,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1934,Best Director,http://www.nndb.com/people/626/000042500/,Cavalcade,Frank Lloyd
6,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1935,Best Director,http://www.nndb.com/people/459/000032363/,It Happened One Night,Frank Capra
7,"Cape Elizabeth, Me",1-Feb-1894,White,Roman Catholic,Bisexual,1936,Best Director,http://www.nndb.com/people/458/000032362/,The Informer,John Ford
8,"Bisacquino, Sicily, Italy",18-May-1897,White,Roman Catholic,Straight,1937,Best Director,http://www.nndb.com/people/459/000032363/,Mr. Deeds Goes to Town,Frank Capra
9,"Los Angeles, Ca",3-Oct-1898,White,Na,Straight,1938,Best Director,http://www.nndb.com/people/380/000044248/,The Awful Truth,Leo McCarey

In [31]:
# update name of column to align with column name of another dataframe we will utilize for our tables
oscars_demo_df.rename(columns={'person':'name'}, inplace=True)

oscars_demo_df.head()

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,biourl,movie,name
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,http://www.nndb.com/people/320/000043191/,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,http://www.nndb.com/people/626/000042500/,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,http://www.nndb.com/people/320/000043191/,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,http://www.nndb.com/people/544/000041421/,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,http://www.nndb.com/people/292/000044160/,Bad Girl,Frank Borzage

In [32]:
#update column name to match others in dataframe, again
oscars_demo_df.rename(columns={'name':'winner'}, inplace=True)

oscars_demo_df.head()

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,biourl,movie,winner
0,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,http://www.nndb.com/people/320/000043191/,Two Arabian Knights,Lewis Milestone
1,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,http://www.nndb.com/people/626/000042500/,The Divine Lady,Frank Lloyd
2,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,http://www.nndb.com/people/320/000043191/,All Quiet on the Western Front,Lewis Milestone
3,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,http://www.nndb.com/people/544/000041421/,Skippy,Norman Taurog
4,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,http://www.nndb.com/people/292/000044160/,Bad Girl,Frank Borzage